#!/bin/bash

[ -z "$1" -o -z "$2" ] && echo "Usage: $0 <indir> <outdir>" && exit 1
indir="${1%/}"
outdir="${2%/}"

for infile in $(find $1 -type f); do
    fulldir="$outdir/$(echo "$infile" | perl -0777 -ne "/^$indir\/(.*\/)?(.*?)$/ && print "'$1')"
    outfile="$fulldir$(echo "$infile" | perl -0777 -ne '/^(.*\/)?(.*?)\.(tpk|png)?$/ && print $2').png"

    mkdir -p "$fulldir"
    ./extract "$infile" "$outfile"

    echo "$outfile: $(jq -r '.scale.original_size | "\(.width)x\(.height)px"' sections/m)" >> sizes.txt
    convert frames/*.png +append "$outfile"
    rm -rf frames sections
done
